module CF
{
    struct Resource {
        string ip;
    };

    interface Application {
        Resource getPort(
            in string idk
        );
    };
};

module DSP
{
    interface ApplicationFactory {
        CF::Application create(
            in any a,
            in string b,
            in string profile
        );
    };

    interface TransporterCtrlUsesPort_v2
    {
        long SendTest();
        long SendPowerPhaseQuery();
        long SendIQSpectrumQuery();
        long SendSignalMessage();
        long getSigBoardInfo();
        long releaseFifo();
    };
};