module CF
{
    struct Resource {
        string ip;
    };

    interface Application {
        Resource getPort(
            in string type
        );
    };

    struct AppConfig {
        string idk;
        string type;
        string file;
    };

    interface ApplicationFactory {
        CF::Application create(
            in string tester,
            in AppConfig config
        );
    };
};

module DSP
{
    interface TransporterCtrlUsesPort_v2
    {
        long SendTest();
        long SendPowerPhaseQuery();
        long SendIQSpectrumQuery();
        long SendSignalMessage();
        long getSigBoardInfo();
        long releaseFifo();
    };
};